# Generated by Django 3.1 on 2020-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preview',
            field=models.ImageField(default='blog_preview_image.jpg', upload_to='blog_preview_image/', verbose_name='Изображение на главной странице'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog_detail_image.jpg', upload_to='blog_detail_image/', verbose_name='Изображение в деталях'),
        ),
    ]
