# Generated by Django 3.1 on 2020-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200827_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.TextField(default=0, max_length=500, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
