# Generated by Django 3.1 on 2020-08-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='preview',
        ),
    ]
