# Generated by Django 3.1 on 2020-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.ImageField(default='blog_detail_image.jpg', upload_to='blog_detail_image/', verbose_name='Изображение'),
        ),
    ]
