# Generated by Django 3.1 on 2020-08-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200827_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
    ]
